version: '3.8'

services:
  document-ocr-api:
    build: .
    ports:
      - "8000:8000"
      - "11434:11434"  # Ollama API
      - "6379:6379"    # Redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ollama_data:/root/.ollama  # Persistir dados do Ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_DEBUG=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || curl -f http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data: 